### ISSUE TITLE
Any plans to publish this to chrome web store?

### ISSUE THREAD

**Issue by gabel** [tmuka/mattermost-chrome-app#1]
Are there plans to drive this forward to a chrome webstore version?

**Comment by tmuka** [comment]
Hi @gabel, I tried to do that one day, but the process of publishing the the chrome web store required the app url defined in the manifest.json to be public so google could validate domain control.  Since my mattermost install is not publically accessible i couldn't move forward with that.  Since that url needs to be changed to your own server url, it probably wouldn't help you if i could publish mine.  There might be a way to add some chrome options that would make that a config variable, and maybe set it by default to some public mattermost server.    Feel free to give it a try if you're so inclined!

**Comment by gabel** [comment]
Thanks for the reply. You're right the mattermost instance URL should be part of an app configuration that needs to be developed. I don't see any spare time for now to do that, but if this changes I'm going to comment here.

**Comment by ssbarnea** [comment]
I am looking forward for the same thing, I am sure that's possible as people can make apps that are connecting to any domain.

**Comment by objarni** [comment]
Yes, the instance URL should be part of the installation process, not part of the chrome application. So, if the environment variable used for URL is null, the app should ask for it first of all.
